### ISSUE TITLE
What this virus is doing?

### ISSUE THREAD

**Issue by MyhGamer** [Ign0r3dH4x0r/GenVirus#1]

**Comment by xastrix** [comment]
is full shit

**Comment by tony656** [comment]
it would be pretty good if he could explain, bcoz i tried it on  y phone and it wiped everythind and sent message to everyone that i hacked them

**Comment by sowmiksudo** [comment]
```Send sms continuously from the device to all phone contacts randomly till mobile balance is nil.
Block sms messenger, etc apps.
Wipe out sd-card data completely.
Hide app icon from app launcher as well as recent category.
Cannot uninstalling this virus app from application manager.
Run in background continuously and gets restarted even after device is turned ON/OFF.
Track the user's interaction by retrieving the applications that user has started. 
```

This virus file is made by @harshalbenake and all the informations are provided by him. I've tested it out and then included it here.
You can find more information here : https://github.com/harshalbenake/Android-Elite-Virus

**Comment by tony656** [comment]
i just figured that out after trying it on my phone and wiped everything
